[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
        "-Clink-arg=-fuse-ld=/usr/local/bin/mold", # Mold!
        # "--cap-lints=warn", # no deny(warnings) for you
        "-Ctarget-cpu=native", # I don't distribute anything
]

[net]
git-fetch-with-cli = true # the git CLI is faster than libgit2
